media:
  input: content/posts
  output: /content/posts
  categories: [image]
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    fields:
      - {name: draft, label: Draft, type: boolean, default: true}
      - {name: title, label: Title, type: string}
      - name: date
        label: Date
        type: date
        options:
          format: YYYY-MM-DDTHH:mm:ssZ
          time: true
      - name: created
        label: Created
        type: date
        options:
          format: YYYY-MM-DD HH:mm
          time: true
      - name: modified
        label: Modified
        type: date
        options:
          format: YYYY-MM-DD HH:mm
          time: true
      - name: categories
        label: Categories
        type: select
        options:
          values:
            - SSG
            - CMS
            - Game Dev
      - name: tags
        label: Tags
        type: select
        options:
          values:
            - hello-world
      - {name: body, label: Body, type: rich-text}
    filename: index.md
    view:
      fields: [title, draft, date]
  - name: about
    label: About
    type: file
    path: content/about/index
    fields:
      - {name: draft, label: Draft, type: boolean, default: true}
      - {name: title, label: Title, type: string}
      - {name: description, label: Description, type: string}
      