media:
  input: assets/images
  output: /assets/images
  categories: [image]
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    fields:
      - {name: draft, label: Draft, type: boolean, default: true}
      - {name: title, label: Title, type: string}
      - name: date
        label: Date
        type: date
        options:
          format: YYYY-MM-DDTHH:mm:ssZ
          time: true
      - name: created
        label: Created
        type: date
        options:
          format: YYYY-MM-DD HH:mm
          time: true
      - name: modified
        label: Modified
        type: date
        options:
          format: YYYY-MM-DD HH:mm
          time: true
      - name: categories
        label: Categories
        type: select
        list: true
        options:
          values:
            - SSG
            - CMS
            - Game Dev
      - name: tags
        label: Tags
        type: string
        list:
          min: 1
          max: 4
      - name: resources
        label: Resources
        type: object
        list:
          min: 2
        fields:
          - name: name
            type: string
            default: featured-image
          - name: src
            label: Image
            type: image
            options:
              input: content/posts
              categories: [image]
      - {name: body, label: Body, type: rich-text}
    filename: index.md
    view:
      fields: [title, draft, date]
  - name: about
    label: About
    type: file
    path: content/about/index.md
    fields:
      - {name: draft, label: Draft, type: boolean, default: true}
      - {name: title, label: Title, type: string}
      - {name: description, label: Description, type: string}
      - name: date
        label: Date
        type: date
        options:
          format: YYYY-MM-DDTHH:mm:ssZ
          time: true
      - name: images
        label: Images
        type: image
        list: true
        options:
          input: content/about
          categories: [image]
      - {name: lightgallery, label: Light Gallery, type: boolean, default: true}
      - name: created
        label: Created
        type: date
        options:
          format: YYYY-MM-DD HH:mm
          time: true
      - name: modified
        label: Modified
        type: date
        options:
          format: YYYY-MM-DD HH:mm
          time: true
      - {name: body, label: Body, type: rich-text}
      