media:
  input: content/posts
  output: /content/posts
  categories: [image]
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    fields:
      - {name: draft, label: Draft, type: boolean, default: true}
      - {name: title, label: Title, type: string}
      - {name: date, label: Date, type: date}
      - name: resources
        label: Resources
        type: object
        fields:
          - name: name
            type: string
            hidden: true
            default: featured-image
          - name: src
            label: Featured Image
            type: image
      - name: categories
        label: Categories
        type: select
        options:
          values:
            SSG
            CMS
            Game Dev
      - {name: body, label: Body, type: rich-text}
    filename: index.md
    view:
      fields: [title, draft, date]