media: assets
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    view:
      fields: [title, date]
    fields:
      - {name: title, label: Title, type: string}
      - {name: date, label: Date, type: date}
      - {name: draft, label: Draft, type: boolean}
      - name: resources
        label: Resources
        type: object
        fields:
          - name: featured-image
            label: Featured Image
            type: image
            fields:
              - name: src
                label: Image
                list: true
                options:
                  path: assets/images
                  extensions: [jpg, png]
                  
      - {name: body, label: Body, type: rich-text}