media: assets
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    view:
      fields: [title, date]
    fields:
      - {name: title, label: Title, type: string}
      - {name: date, label: Date, type: date}
      - {name: draft, label: Draft, type: boolean, default: true}
      - name: resources
        label: Resources
        type: object
        fields:
          - name: name
            label: Name
            type: string
            hidden: true
            default: featured-image
      - {name: body, label: Body, type: rich-text}